apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: injonge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/injonge-workforce-payroll-portal/infra-repo.git 
    targetRevision: main
    path: apps/injonge
  
  destination:
    server: https://kubernetes.default.svc
    namespace: injonge
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
  
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: backend-secrets
    jsonPointers:
    - /data